// import { streetName, communityName, gridName, buildNature, buildType, isTrue, useMode, format, buildingNo, sex, marriageStatus, education, personnelAttributes, special, relationship, keyServicePersonType, keyManagePersonType } from '@/config/common'
import { getHouseList,getPeopleList,getPeopleByHouseList } from '@/api/ActualInfo/build'

// 启用序号列会与sortable拖拽发生冲突   不要一起使用!!!!
export function renderTable() {
  const houseTableConfig = {
    name: 'table1',
    data: [],
    pagination: false, // 开启分页器
    mutiSelect: false, // 开启选择
    method: getHouseList, // 請求api
    index: false, // 是否启用序号列 
    total: 0,
    isSortable: false, // 是否开启拖拽
    columns: [
      {
        prop: 'unitNumber',
        label: '单元号',
        minWidth: '120',
      },
      { prop: 'house', label: '房间号', minWidth: '120' },
      { prop: 'userName', label: '使用者姓名', minWidth: '120' },
      { prop: 'userPhone', label: '使用者联系方式', minWidth: '120' },
    ],
  }
  const peopleTableConfig = {
    name: 'table2',
    data: [],
    pagination: false, // 开启分页器
    mutiSelect: false, // 开启选择
    method: getPeopleList, // 請求api
    index: false, // 是否启用序号列
    total: 0,
    isSortable: false, // 是否开启拖拽
    columns: [
      {
        prop: 'name',
        label: '姓名',
      },
      { prop: 'idcard', label: '身份证号', minWidth: '120' },
      // { prop: 'residenceNow', label: '具体住址',minWidth:'200'},
    ],
  }
  const peopleByHouseTableConfig = {
    name: 'table3',
    data: [],
    pagination: false, // 开启分页器
    mutiSelect: false, // 开启选择
    method: getPeopleByHouseList, // 請求api
    index: false, // 是否启用序号列
    total: 0,
    isSortable: false, // 是否开启拖拽
    columns: [
      {
        prop: 'name',
        label: '姓名',
      },
      { prop: 'idcard', label: '身份证号', minWidth: '120' },
      // { prop: 'residenceNow', label: '具体住址',},
    ],
  }
  const DrugFormConfig = {
    gutter: 10,
    formItems: [
      {
        type: 'slot',
        label: '组织结构',
        span: 8,
        slotName:'tree',
        prop:'streetCode'
      },
      {
        type: 'slot',
        label: '',
        span: 8,
        slotName:'communityCode',
        prop:'communityCode'
      },
      {
        type: 'slot',
        label: '',
        span: 6,
        slotName:'officeCode',
        prop:'officeCode'
      },
      {
        type: 'slot',
        label: '楼栋',
        prop: 'buildingId',
        // value: '',
        slotName:'buildingId',
        // placeholder: '请选择楼栋名称',
        isClearable: true,
        span: 11,
      },
      {
        type: 'slot',
        label: '房屋',
        prop: 'houseId',
        slotName:'house',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '身份证号',
        prop: 'idCard',
        value: '',
        placeholder: '请输入身份证号',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '姓名',
        prop: 'staffName',
        value: '',
        placeholder: '请输入重点人员姓名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '曾用名',
        prop: 'beforeName',
        value: '',
        placeholder: '请输入重点人员曾用名',
        isClearable: true,
        span: 11,
      },
      
      {
        type: 'selectSearch',
        label: '性别',
        prop: 'gender',
        value: '',
        code: '1009',
        placeholder: '请选择重点人员性别',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '出生日期',
        prop: 'birthDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '民族',
        prop: 'nation',
        value: '',
        code: '1021',
        placeholder: '请选择重点人员民族',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '籍贯',
        prop: 'nativePlace',
        value: '',
        placeholder: '请输入重点人员籍贯',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '婚姻状态',
        prop: 'marriageStatus',
        value: '',
        code: '1010',
        placeholder: '请选择婚姻状态',
        isClearable: true,
        span: 11, 
      },
      {
        type: 'selectSearch',
        label: '政治面貌',
        prop: 'politicalOutlook',
        value: '',
        code: '1050',
        placeholder: '请选择政治面貌',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '学历',
        prop: 'education',
        value: '',
        code: '1011',
        placeholder: '请选择学历',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '宗教信仰',
        prop: 'religiousBelief',
        value: '',
        placeholder: '请输入宗教信仰',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '职业类别',
        prop: 'staffType',
        span: 11,
        code : '1032',
        placeholder: '请选择职业类别',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '服务处所',
        prop: 'servicePlace',
        value: '',
        placeholder: '请输入服务处所',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '联系方式',
        prop: 'contactPhone',
        value: '',
        placeholder: '请输入联系方式',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '户籍地',
        prop: 'domicile',
        value: '',
        placeholder: '请输入户籍地',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '户籍详址',
        prop: 'domicileDetail',
        value: '',
        placeholder: '请输入户籍详址',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '现在地',
        prop: 'residenceNow',
        value: '',
        placeholder: '请输入现在地',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '现住详址',
        prop: 'residenceNowDetail',
        value: '',
        placeholder: '请输入现住详址',
        isClearable: true,
        span: 11,
      },
     
      {
        type: 'Input',
        label: '职业',
        prop: 'occupation',
        value: '',
        placeholder: '请输入职业',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '初次发现日期',
        prop: 'firstDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '管控情况',
        prop: 'controlSituation',
        span: 11,
        code : '1039',// 改 
        placeholder: '请选择职业类别',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '管控人姓名',
        prop: 'controlPer',
        value: '',
        placeholder: '请输入管控人姓名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '管控人联系方式',
        prop: 'controlPerPhone',
        value: '',
        placeholder: '请输入管控人联系方式',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '帮扶情况',
        prop: 'helpSituation',
        value: '',
        placeholder: '请输入帮扶情况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '帮扶人姓名',
        prop: 'helpPer',
        value: '',
        placeholder: '请输入帮扶人姓名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '帮扶人联系方式',
        prop: 'helpPerPhone',
        value: '',
        placeholder: '请输入帮扶人联系方式',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '有无犯罪史',
        prop: 'isCrime',
        span: 11,
        code :'1040',// 改 
        placeholder: '请选择犯罪史',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '犯罪情况',
        prop: 'crimeSituation',
        span: 11,
        placeholder: '请选输入犯罪情况',
        isClearable: true,
      },
      {
        type: 'selectSearch',
        label: '吸毒原因',
        prop: 'drugReason',
        span: 11,
        code :'1041',// 改 
        placeholder: '请选择吸毒原因',
        isClearable: true,
      },
      {
        type: 'selectSearch',
        label: '吸毒后果',
        prop: 'drugConsequence',
        span: 11,
        code :'1042',// 改 
        placeholder: '请选择吸毒后果',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '包案人姓名',
        prop: 'contractorName',
        span: 11,
        placeholder: '请选输入包案人姓名',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '包案人职位',
        prop: 'contractorPosition',
        span: 11,
        placeholder: '请选输入包案人职位',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '包案人电话',
        prop: 'contractorPhone',
        span: 11,
        placeholder: '请选输入包案人电话',
        isClearable: true,
      },
      {
        type: 'textarea',
        label: '备注',
        prop: 'remarks',
        value: '',
        placeholder: '请输入备注',
        isClearable: true,
        span: 22,
      },
    ],
    rules: {
      streetCode: [{ required: true, message: '请选择街道', trigger: ['blur', 'change'] }],
      officeCode: [{ required: true, message: '请选择网格', trigger: ['blur', 'change'] }],
      buildingId: [{ required: true, message: '请选择楼栋', trigger: ['blur', 'change'] }],
      communityCode: [{ required: true, message: '请选择社区', trigger: ['blur', 'change'] }],
      idCard: [{ required: true, message: '请输入身份证号', trigger: ['blur', 'change'] }],
      staffName: [{ required: true, message: '请输入姓名', trigger: ['blur', 'change'] }],
      houseId: [{ required: true, message: '请选择房屋', trigger: ['blur', 'change'] }],
    },
    
  }
  const ReleaseFormConfig = {
    gutter: 10,
    formItems: [
      {
        type: 'slot',
        label: '组织结构',
        span: 8,
        slotName:'tree',
        value:'',
        prop:'streetCode'
      },
      {
        type: 'slot',
        label: '',
        span: 8,
        slotName:'communityCode',
        prop:'communityCode'
      },
      {
        type: 'slot',
        label: '',
        span: 6,
        slotName:'officeCode',
        prop:'officeCode'
      },
      {
        type: 'slot',
        label: '楼栋',
        prop: 'buildingId',
        slotName:'buildingId',
        span: 11,
      },
      {
        type: 'slot',
        label: '房屋',
        prop: 'houseId',
        // value: '',
        slotName:'house',
        span: 11,
      },
      {
        type: 'Input',
        label: '身份证号',
        prop: 'idCard',
        value: '',
        placeholder: '请输入身份证号',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '姓名',
        prop: 'staffName',
        value: '',
        placeholder: '请输入重点人员姓名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '曾用名',
        prop: 'beforeName',
        value: '',
        placeholder: '请输入重点人员曾用名',
        isClearable: true,
        span: 11,
      },
      
      {
        type: 'selectSearch',
        label: '性别',
        prop: 'gender',
        value: '',
        code: '1009',
        placeholder: '请选择重点人员性别',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '出生日期',
        prop: 'birthDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '民族',
        prop: 'nation',
        value: '',
        code: '1021',
        placeholder: '请选择重点人员民族',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '籍贯',
        prop: 'nativePlace',
        value: '',
        placeholder: '请输入重点人员籍贯',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '婚姻状态',
        prop: 'marriageStatus',
        value: '',
        code: '1010',
        placeholder: '请选择婚姻状态',
        isClearable: true,
        span: 11, 
      },
      {
        type: 'selectSearch',
        label: '政治面貌',
        prop: 'politicalOutlook',
        value: '',
        code: '1050',
        placeholder: '请选择政治面貌',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '学历',
        prop: 'education',
        value: '',
        code: '1011',
        placeholder: '请选择学历',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '宗教信仰',
        prop: 'religiousBelief',
        value: '',
        placeholder: '请输入宗教信仰',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '职业类别',
        prop: 'staffType',
        span: 11,
        code : '1032',
        placeholder: '请选择职业类别',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '服务处所',
        prop: 'servicePlace',
        value: '',
        placeholder: '请输入服务处所',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '联系方式',
        prop: 'contactPhone',
        value: '',
        placeholder: '请输入联系方式',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '户籍地',
        prop: 'domicile',
        value: '',
        placeholder: '请输入户籍地',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '户籍详址',
        prop: 'domicileDetail',
        value: '',
        placeholder: '请输入户籍详址',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '现在地',
        prop: 'residenceNow',
        value: '',
        placeholder: '请输入现在地',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '现住详址',
        prop: 'residenceNowDetail',
        value: '',
        placeholder: '请输入现住详址',
        isClearable: true,
        span: 11,
      },
      
      {
        type: 'Input',
        label: '职业',
        prop: 'occupation',
        value: '',
        placeholder: '请输入职业',
        isClearable: true,
        span: 11,
      },
      //gai
      {
        type: 'selectSearch',
        label: '是否累犯',
        prop: 'isRecidivist',
        span: 11,
        code : '1006',
        placeholder: '请选择是否累犯',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '原罪名',
        prop: 'charge',
        value: '',
        placeholder: '请输入原罪名',
        isClearable: true,
        span: 11,
      }, 
      {
        type: 'Input',
        label: '原判刑期',
        prop: 'sentenceDate',
        value: '',
        placeholder: '请输入原判刑期',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '释放日期',
        prop: 'releaseDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '危险评估性',
        prop: 'dangerAssess',
        span: 11,
        code : '1033',
        placeholder: '请选择危险评估性',
        isClearable: true,
      },
      {
        type: 'date',
        label: '衔接日期',
        prop: 'joinDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '衔接情况',
        prop: 'joinJituation',
        span: 11,
        code : '1034',
        placeholder: '请选择衔接情况',
        isClearable: true,
      },
      {
        type: 'date',
        label: '安置日期',
        prop: 'resettleDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '安置情况',
        prop: 'resettle',
        span: 11,
        code : '1035',
        placeholder: '请选择安置情况',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '未安置原因',
        prop: 'notResettleReson',
        value: '',
        placeholder: '请输入未安置原因',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '帮教情况',
        prop: 'helpSituation',
        value: '',
        placeholder: '请输入帮教情况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '是否重新犯罪',
        prop: 'isRecidivist',
        span: 11,
        code : '1006',
        placeholder: '请选择是否重新犯罪',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '重新犯罪罪名',
        prop: 'recidivistCharge',
        value: '',
        placeholder: '请输入重新犯罪罪名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '包案人姓名',
        prop: 'contractorName',
        value: '',
        placeholder: '请输入包案人姓名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '包案人职位',
        prop: 'contractorPosition',
        value: '',
        placeholder: '请输入包案人职位',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '包案人电话',
        prop: 'contractorPhone',
        value: '',
        placeholder: '请输入包案人电话',
        isClearable: true,
        span: 11,
      },
      {
        type: 'textarea',
        label: '备注',
        prop: 'remarks',
        value: '',
        placeholder: '请输入备注',
        isClearable: true,
        span: 22,
      },
    ],
    rules: {
      streetCode: [{ required: true, message: '请选择街道', trigger: ['blur', 'change'] }],
      officeCode: [{ required: true, message: '请选择网格', trigger: ['blur', 'change'] }],
      buildingId: [{ required: true, message: '请选择楼栋', trigger: ['blur', 'change'] }],
      communityCode: [{ required: true, message: '请选择社区', trigger: ['blur', 'change'] }],
      idCard: [{ required: true, message: '请输入身份证号', trigger: ['blur', 'change'] }],
      staffName: [{ required: true, message: '请输入姓名', trigger: ['blur', 'change'] }],
      houseId: [{ required: true, message: '请选择房屋', trigger: ['blur', 'change'] }],
    },
    
  }
  const RrectifyFormConfig = {
    gutter: 10,
    formItems: [
      {
        type: 'slot',
        label: '组织结构',
        span: 8,
        slotName:'tree',
        prop:'streetCode'
      },
      {
        type: 'slot',
        label: '',
        span: 8,
        slotName:'communityCode',
        prop:'communityCode'
      },
      {
        type: 'slot',
        label: '',
        span: 6,
        slotName:'officeCode',
        prop:'officeCode'
      },
      {
        type: 'slot',
        label: '楼栋',
        prop: 'buildingId',
        slotName:'buildingId',
        isClearable: true,
        span: 11,
      },
      {
        type: 'slot',
        label: '房屋',
        prop: 'houseId',
        slotName:'house',
        span: 11,
      },
      {
        type: 'Input',
        label: '身份证号',
        prop: 'idCard',
        value: '',
        placeholder: '请输入身份证号',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '姓名',
        prop: 'staffName',
        value: '',
        placeholder: '请输入重点人员姓名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '曾用名',
        prop: 'beforeName',
        value: '',
        placeholder: '请输入重点人员曾用名',
        isClearable: true,
        span: 11,
      },
      
      {
        type: 'selectSearch',
        label: '性别',
        prop: 'gender',
        value: '',
        code: '1009',
        placeholder: '请选择重点人员性别',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '出生日期',
        prop: 'birthDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '民族',
        prop: 'nation',
        value: '',
        code: '1021',
        placeholder: '请选择重点人员民族',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '籍贯',
        prop: 'nativePlace',
        value: '',
        placeholder: '请输入重点人员籍贯',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '婚姻状态',
        prop: 'marriageStatus',
        value: '',
        code: '1010',
        placeholder: '请选择婚姻状态',
        isClearable: true,
        span: 11, 
      },
      {
        type: 'selectSearch',
        label: '政治面貌',
        prop: 'politicalOutlook',
        value: '',
        code: '1050',
        placeholder: '请选择政治面貌',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '学历',
        prop: 'education',
        value: '',
        code: '1011',
        placeholder: '请选择学历',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '宗教信仰',
        prop: 'religiousBelief',
        value: '',
        placeholder: '请输入宗教信仰',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '职业类别',
        prop: 'staffType',
        span: 11,
        code : '1032',
        placeholder: '请选择职业类别',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '服务处所',
        prop: 'servicePlace',
        value: '',
        placeholder: '请输入服务处所',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '联系方式',
        prop: 'contactPhone',
        value: '',
        placeholder: '请输入联系方式',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '户籍地',
        prop: 'domicile',
        value: '',
        placeholder: '请输入户籍地',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '户籍详址',
        prop: 'domicileDetail',
        value: '',
        placeholder: '请输入户籍详址',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '现在地',
        prop: 'residenceNow',
        value: '',
        placeholder: '请输入现在地',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '现住详址',
        prop: 'residenceNowDetail',
        value: '',
        placeholder: '请输入现住详址',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '职业',
        prop: 'occupation',
        value: '',
        placeholder: '请输入职业',
        isClearable: true,
        span: 11,
      },
      //gai
      {
        type: 'Input',
        label: '矫正人员编号',
        prop: 'rectifyNO',
        value: '',
        placeholder: '请输入矫正人员编号',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '原羁押场所',
        prop: 'custodyPlace',
        value: '',
        placeholder: '请输入原羁押场所',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '矫正类别',
        prop: 'rectifyType',
        value: '',
        placeholder: '请输入矫正类别',
        code: '1036',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '事项类别',
        prop: 'caseType',
        value: '',
        code: '1025',
        placeholder: '请输入事项类别',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '具体罪名',
        prop: 'accusation',
        value: '',
        placeholder: '请输入具体罪名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '原判刑期',
        prop: 'sentenceDate',
        value: '',
        placeholder: '请输入原判刑期',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '原判刑期开始时间',
        prop: 'sentenceStartDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '原判刑期结束时间',
        prop: 'sentenceEndDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '矫正开始日期',
        prop: 'rectifyStartDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '矫正结束日期',
        prop: 'rectifyEndDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '接收方式',
        prop: 'receiveMode',
        value: '',
        placeholder: '请选择接收方式',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '四史情况',
        prop: 'fourHistories',
        value: '',
        placeholder: '请选择四史情况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '是否累惯犯',
        prop: 'isRecidivist',
        value: '',
        placeholder: '请选择是否累惯犯',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '三涉情况',
        prop: 'threeInvolved',
        value: '',
        placeholder: '请选择三涉情况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '是否建立矫正小组',
        prop: 'isRectifyTeam',
        value: '',
        placeholder: '请选择是否建立矫正小组',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '矫正人员小组情况',
        prop: 'rectifyTeamPer',
        value: '',
        placeholder: '请输入矫正人员小组情况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '矫正解除类型',
        prop: 'rectifyReleaseType',
        span: 11,
        code : '1006',
        placeholder: '请选择矫正解除类型',
        isClearable: true,
      },
      {
        type: 'selectSearch',
        label: '是否有脱管',
        prop: 'isTrusteeship',
        span: 11,
        code : '1006',
        placeholder: '请选择是否有脱管',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '脱管原因',
        prop: 'trusteeshipReason',
        value: '',
        placeholder: '请输入脱管原因',
        isClearable: true,
        span: 11,
      }, 
      {
        type: 'Input',
        label: '检查监督托管情况',
        prop: 'checkTrusteeship',
        value: '',
        placeholder: '请输入检查监督托管情况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '托管纠正情况',
        prop: 'trusteeshipRectify',
        value: '',
        placeholder: '请输入托管纠正情况',
        isClearable: true,
        span: 11,
      },  
      {
        type: 'selectSearch',
        label: '是否有漏管',
        prop: 'isMissmanage',
        span: 11,
        code : '1006',
        placeholder: '请选择是否有漏管',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '漏管原因',
        prop: 'missmanageReason',
        value: '',
        placeholder: '请输入漏管原因',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '检察监督漏管情况',
        prop: 'checkMissmanage',
        value: '',
        placeholder: '请输入检察监督漏管情况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '漏管纠正情况',
        prop: 'rectifyMissmanage',
        value: '',
        placeholder: '请输入漏管纠正情况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '检查情况',
        prop: 'inspection',
        value: '',
        placeholder: '请输入检查情况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '刑罚变更执行情况',
        prop: 'penaltyChangeType',
        value: '',
        placeholder: '请输入刑罚变更执行情况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '是否重新犯罪',
        prop: 'isRecidivist',
        span: 11,
        code : '1006',
        placeholder: '请选择是否重新犯罪',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '重新犯罪名称',
        prop: 'recidivistCharge',
        value: '',
        placeholder: '请输入重新犯罪名称',
        isClearable: true,
        span: 11,
      },
      
      {
        type: 'Input',
        label: '包案人姓名',
        prop: 'contractorName',
        value: '',
        placeholder: '请输入包案人姓名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '包案人职位',
        prop: 'contractorPosition',
        value: '',
        placeholder: '请输入包案人职位',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '包案人电话',
        prop: 'contractorPhone',
        value: '',
        placeholder: '请输入包案人电话',
        isClearable: true,
        span: 11,
      },
      {
        type: 'textarea',
        label: '备注',
        prop: 'remarks',
        value: '',
        placeholder: '请输入备注',
        isClearable: true,
        span: 22,
      },
    ],
    rules: {
      streetCode: [{ required: true, message: '请选择街道', trigger: ['blur', 'change'] }],
      officeCode: [{ required: true, message: '请选择网格', trigger: ['blur', 'change'] }],
      buildingId: [{ required: true, message: '请选择楼栋', trigger: ['blur', 'change'] }],
      communityCode: [{ required: true, message: '请选择社区', trigger: ['blur', 'change'] }],
      idCard: [{ required: true, message: '请输入身份证号', trigger: ['blur', 'change'] }],
      staffName: [{ required: true, message: '请输入姓名', trigger: ['blur', 'change'] }],
      houseId: [{ required: true, message: '请选择房屋', trigger: ['blur', 'change'] }],
    },
    
  }
  const MentaldisordersFormConfig = {
    gutter: 10,
    formItems: [
      {
        type: 'slot',
        label: '组织结构',
        span: 8,
        slotName:'tree',
        prop:'streetCode'
      },
      {
        type: 'slot',
        label: '',
        span: 8,
        slotName:'communityCode',
        prop:'communityCode'
      },
      {
        type: 'slot',
        label: '',
        span: 6,
        slotName:'officeCode',
        prop:'officeCode'
      },
      {
        type: 'slot',
        label: '楼栋',
        prop: 'buildingId',
        // value: '',
        slotName:'buildingId',
        // placeholder: '请选择楼栋名称',
        isClearable: true,
        span: 11,
      },
      {
        type: 'slot',
        label: '房屋',
        prop: 'houseId',
        // value: '',
        slotName:'house',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '身份证号',
        prop: 'idCard',
        value: '',
        placeholder: '请输入身份证号',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '姓名',
        prop: 'staffName',
        value: '',
        placeholder: '请输入重点人员姓名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '曾用名',
        prop: 'beforeName',
        value: '',
        placeholder: '请输入重点人员曾用名',
        isClearable: true,
        span: 11,
      },
      
      {
        type: 'selectSearch',
        label: '性别',
        prop: 'gender',
        value: '',
        code: '1009',
        placeholder: '请选择重点人员性别',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '出生日期',
        prop: 'birthDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '民族',
        prop: 'nation',
        value: '',
        code: '1021',
        placeholder: '请选择重点人员民族',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '籍贯',
        prop: 'nativePlace',
        value: '',
        placeholder: '请输入重点人员籍贯',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '婚姻状态',
        prop: 'marriageStatus',
        value: '',
        code: '1010',
        placeholder: '请选择婚姻状态',
        isClearable: true,
        span: 11, 
      },
      {
        type: 'selectSearch',
        label: '政治面貌',
        prop: 'politicalOutlook',
        value: '',
        code: '1050',
        placeholder: '请选择政治面貌',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '学历',
        prop: 'education',
        value: '',
        code: '1011',
        placeholder: '请选择学历',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '宗教信仰',
        prop: 'religiousBelief',
        value: '',
        placeholder: '请输入宗教信仰',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '职业类别',
        prop: 'staffType',
        span: 11,
        code : '1032',
        placeholder: '请选择职业类别',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '服务处所',
        prop: 'servicePlace',
        value: '',
        placeholder: '请输入服务处所',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '联系方式',
        prop: 'contactPhone',
        value: '',
        placeholder: '请输入联系方式',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '户籍地',
        prop: 'domicile',
        value: '',
        placeholder: '请输入户籍地',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '户籍详址',
        prop: 'domicileDetail',
        value: '',
        placeholder: '请输入户籍详址',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '现在地',
        prop: 'residenceNow',
        value: '',
        placeholder: '请输入现在地',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '现住详址',
        prop: 'residenceNowDetail',
        value: '',
        placeholder: '请输入现住详址',
        isClearable: true,
        span: 11,
      },
      
      {
        type: 'Input',
        label: '职业',
        prop: 'occupation',
        value: '',
        placeholder: '请输入职业',
        isClearable: true,
        span: 11,
      },
      //gai
      {
        type: 'selectSearch',
        label: '家庭经济状况',
        prop: 'economySituation',
        value: '',
        placeholder: '请选择家庭经济状况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '是否纳入低保',
        prop: 'isIncludedInTheLow',
        value: '',
        placeholder: '请选择是否纳入低保',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '监护人公民身份号码',
        prop: 'guardianIdCard',
        value: '',
        placeholder: '请输入监护人公民身份号码',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '监护人姓名',
        prop: 'guardianName',
        value: '',
        placeholder: '请输入监护人姓名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '监护人联系方式',
        prop: 'guardianPhone',
        value: '',
        placeholder: '请输入监护人联系方式',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '初次发病日期',
        prop: 'firstMorbidityDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '目前诊断类型',
        prop: 'diagnosisType',
        value: '',
        placeholder: '请选择目前诊断类型',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '有无肇事肇祸史',
        prop: 'isAccident',
        value: '',
        placeholder: '请选择有无肇事肇祸史',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '肇事肇祸次数',
        prop: 'accidentNum',
        value: '',
        placeholder: '请输入肇事肇祸次数',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '上次肇事肇祸日期',
        prop: 'lastAccidentDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '目前危险性评估等级',
        prop: 'dangerAssess',
        value: '',
        placeholder: '请选择目前危险性评估等级',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '治疗情况',
        prop: 'treatSituation',
        value: '',
        placeholder: '请输入治疗情况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '治疗医院名称',
        prop: 'treatPlace',
        value: '',
        placeholder: '请输入治疗医院名称',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '实施住院治疗原因',
        prop: 'hospitalizationReason',
        value: '',
        code:'',
        placeholder: '请输入实施住院治疗原因',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '接收康复训练机构名称',
        prop: 'rehabilitationPlace',
        value: '',
        placeholder: '请输入接收康复训练机构名称',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '参与管理人员',
        prop: 'managePer',
        code:'',
        placeholder: '请输入参与管理人员',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '帮扶情况',
        prop: 'helpType',
        code:'',
        placeholder: '请选择帮扶情况',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '包案人姓名',
        prop: 'contractorName',
        value: '',
        placeholder: '请输入包案人姓名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '包案人职位',
        prop: 'contractorPosition',
        value: '',
        placeholder: '请输入包案人职位',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '包案人电话',
        prop: 'contractorPhone',
        value: '',
        placeholder: '请输入包案人电话',
        isClearable: true,
        span: 11,
      },
      {
        type: 'textarea',
        label: '备注',
        prop: 'remarks',
        value: '',
        placeholder: '请输入备注',
        isClearable: true,
        span: 22,
      },
    ],
    rules: {
      streetCode: [{ required: true, message: '请选择街道', trigger: ['blur', 'change'] }],
      officeCode: [{ required: true, message: '请选择网格', trigger: ['blur', 'change'] }],
      buildingId: [{ required: true, message: '请选择楼栋', trigger: ['blur', 'change'] }],
      communityCode: [{ required: true, message: '请选择社区', trigger: ['blur', 'change'] }],
      idCard: [{ required: true, message: '请输入身份证号', trigger: ['blur', 'change'] }],
      staffName: [{ required: true, message: '请输入姓名', trigger: ['blur', 'change'] }],
      houseId: [{ required: true, message: '请选择房屋', trigger: ['blur', 'change'] }],
    },
    
  }
  const PetitionFormConfig = {
    gutter: 10,
    formItems: [
      {
        type: 'slot',
        label: '组织结构',
        span: 8,
        slotName:'tree',
        prop:'streetCode'
      },
      {
        type: 'slot',
        label: '',
        span: 8,
        slotName:'communityCode',
        prop:'communityCode'
      },
      {
        type: 'slot',
        label: '',
        span: 6,
        slotName:'officeCode',
        prop:'officeCode'
      },
      {
        type: 'slot',
        label: '楼栋',
        prop: 'buildingId',
        // value: '',
        slotName:'buildingId',
        // placeholder: '请选择楼栋名称',
        isClearable: true,
        span: 11,
      },
      {
        type: 'slot',
        label: '房屋',
        prop: 'houseId',
        // value: '',
        slotName:'house',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '身份证号',
        prop: 'idCard',
        value: '',
        placeholder: '请输入身份证号',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '姓名',
        prop: 'staffName',
        value: '',
        placeholder: '请输入重点人员姓名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '曾用名',
        prop: 'beforeName',
        value: '',
        placeholder: '请输入重点人员曾用名',
        isClearable: true,
        span: 11,
      },
      
      {
        type: 'selectSearch',
        label: '性别',
        prop: 'gender',
        value: '',
        code: '1009',
        placeholder: '请选择重点人员性别',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '出生日期',
        prop: 'birthDate',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '民族',
        prop: 'nation',
        value: '',
        code: '1021',
        placeholder: '请选择重点人员民族',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '籍贯',
        prop: 'nativePlace',
        value: '',
        placeholder: '请输入重点人员籍贯',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '婚姻状态',
        prop: 'marriageStatus',
        value: '',
        code: '1010',
        placeholder: '请选择婚姻状态',
        isClearable: true,
        span: 11, 
      },
      {
        type: 'selectSearch',
        label: '政治面貌',
        prop: 'politicalOutlook',
        value: '',
        code: '1050',
        placeholder: '请选择政治面貌',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '学历',
        prop: 'education',
        value: '',
        code: '1011',
        placeholder: '请选择学历',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '宗教信仰',
        prop: 'religiousBelief',
        value: '',
        placeholder: '请输入宗教信仰',
        isClearable: true,
        span: 11,
      },
      {
        type: 'selectSearch',
        label: '职业类别',
        prop: 'staffType',
        span: 11,
        code : '1032',
        placeholder: '请选择职业类别',
        isClearable: true,
      },
      {
        type: 'Input',
        label: '服务处所',
        prop: 'servicePlace',
        value: '',
        placeholder: '请输入服务处所',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '联系方式',
        prop: 'contactPhone',
        value: '',
        placeholder: '请输入联系方式',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '户籍地',
        prop: 'domicile',
        value: '',
        placeholder: '请输入户籍地',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '户籍详址',
        prop: 'domicileDetail',
        value: '',
        placeholder: '请输入户籍详址',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '现在地',
        prop: 'residenceNow',
        value: '',
        placeholder: '请输入现在地',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '现住详址',
        prop: 'residenceNowDetail',
        value: '',
        placeholder: '请输入现住详址',
        isClearable: true,
        span: 11,
      },
      
      {
        type: 'Input',
        label: '职业',
        prop: 'occupation',
        value: '',
        placeholder: '请输入职业',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '上访日期',
        prop: 'petitionTime',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '上访次数',
        prop: 'petitionNumber',
        value: '',
        placeholder: '请输入上访次数',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '上访原因',
        prop: 'petitionReason',
        value: '',
        placeholder: '请输入上访原因',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '包案人姓名',
        prop: 'contractorName',
        value: '',
        placeholder: '请输入包案人姓名',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '包案人职位',
        prop: 'contractorPosition',
        value: '',
        placeholder: '请输入包案人职位',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '包案人电话',
        prop: 'contractorPhone',
        value: '',
        placeholder: '请输入包案人电话',
        isClearable: true,
        span: 11,
      },
      {
        type: 'textarea',
        label: '备注',
        prop: 'remarks',
        value: '',
        placeholder: '请输入备注',
        isClearable: true,
        span: 22,
      },
    ],
    rules: {
      streetCode: [{ required: true, message: '请选择街道', trigger: ['blur', 'change'] }],
      officeCode: [{ required: true, message: '请选择网格', trigger: ['blur', 'change'] }],
      buildingId: [{ required: true, message: '请选择楼栋', trigger: ['blur', 'change'] }],
      communityCode: [{ required: true, message: '请选择社区', trigger: ['blur', 'change'] }],
      idCard: [{ required: true, message: '请输入身份证号', trigger: ['blur', 'change'] }],
      staffName: [{ required: true, message: '请输入姓名', trigger: ['blur', 'change'] }],
      houseId: [{ required: true, message: '请选择房屋', trigger: ['blur', 'change'] }],
    },
    
  }
  return {
    DrugFormConfig,
    houseTableConfig,
    peopleTableConfig,
    peopleByHouseTableConfig,
    ReleaseFormConfig,
    RrectifyFormConfig,
    MentaldisordersFormConfig,
    PetitionFormConfig
  }
}
