// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es/el-breadcrumb')['default']
    ElBreadcrumbItem: typeof import('element-plus/es/el-breadcrumb-item')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElCard: typeof import('element-plus/es/el-card')['default']
    ElCheckbox: typeof import('element-plus/es/el-checkbox')['default']
    ElCol: typeof import('element-plus/es/el-col')['default']
    ElDatePicker: typeof import('element-plus/es/el-date-picker')['default']
    ElDialog: typeof import('element-plus/es/el-dialog')['default']
    ElDropdown: typeof import('element-plus/es/el-dropdown')['default']
    ElDropdownItem: typeof import('element-plus/es/el-dropdown-item')['default']
    ElDropdownMenu: typeof import('element-plus/es/el-dropdown-menu')['default']
    ElForm: typeof import('element-plus/es/el-form')['default']
    ElFormItem: typeof import('element-plus/es/el-form-item')['default']
    ElImage: typeof import('element-plus/es/el-image')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElLink: typeof import('element-plus/es/el-link')['default']
    ElMenu: typeof import('element-plus/es/el-menu')['default']
    ElMenuItem: typeof import('element-plus/es/el-menu-item')['default']
    ElOption: typeof import('element-plus/es/el-option')['default']
    ElPagination: typeof import('element-plus/es/el-pagination')['default']
    ElPopconfirm: typeof import('element-plus/es/el-popconfirm')['default']
    ElProgress: typeof import('element-plus/es/el-progress')['default']
    ElRow: typeof import('element-plus/es/el-row')['default']
    ElSelect: typeof import('element-plus/es/el-select')['default']
    ElSubmenu: typeof import('element-plus/es/el-submenu')['default']
    ElTable: typeof import('element-plus/es/el-table')['default']
    ElTableColumn: typeof import('element-plus/es/el-table-column')['default']
    ElTabPane: typeof import('element-plus/es/el-tab-pane')['default']
    ElTabs: typeof import('element-plus/es/el-tabs')['default']
    ElTag: typeof import('element-plus/es/el-tag')['default']
    ElTooltip: typeof import('element-plus/es/el-tooltip')['default']
    ElTree: typeof import('element-plus/es/el-tree')['default']
    ElTreeV2: typeof import('element-plus/es/el-tree-v2')['default']
    ElUpload: typeof import('element-plus/es/el-upload')['default']
    Form: typeof import('./src/components/Form/index.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderSidebar: typeof import('./src/components/Header-sidebar.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
  }
}

export { }
