// import {  } from '@/api/SocialGovernance/build'
import validator from "@/utils/validator"

export function renderTable() {
    const InfoFormConfig = {
        gutter:10,
        labelWidth:'220px',
        position:'right',
        formItems: [
            {
                type: 'slot',
                label: '组织机构',
                prop: 'officeName',
                slotName:'status',
                span: 11,
              },
              {
                type: 'date',
                label: '办结时限',
                prop: 'concludeTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '联系人',
                prop: 'contacts',
                value: '',
                placeholder: '请输入联系人',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '联系电话',
                prop: 'contactNumber',
                value: '',
                placeholder: '请输入联系电话',
                isClearable: true,
                span: 11,
              },
              {
                type: 'textarea',
                label: '问题描述',
                prop: 'problemDescription',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'textarea',
                label: '转办意见',
                prop: 'transferOpinions',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '工单编号',
                prop: 'orderNo',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'date',
                label: '接收时间',
                prop: 'receivingTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '地址',
                prop: 'address',
                value: '',
                placeholder: '请输入地址',
                isClearable: true,
                span: 11,
              },
              {
                type: 'selectSearch',
                label: '紧急程度',
                prop: 'urgency',
                placeholder: '请选择紧急程度',
                code:'1076',
                isClearable: true,
                span: 11,
              },
              {
                type: 'selectSearch',
                label: '是否保密',
                prop: 'isSecrecy',
                code:'1077',
                isClearable: true,
                span: 11,
              },
              {
                type: 'selectSearch',
                label: '是否回复',
                prop: 'isReply',
                code:'1006',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '回复备注',
                prop: 'replyRemarks',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '办理轨迹',
                prop: 'handlingTrack',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '转办人',
                prop: 'transferor',
                value: '',
                placeholder: '请输入转办人',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '备注',
                prop: 'remarks',
                value: '',
                placeholder: '请输入备注',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '受理类型',
                prop: 'acceptanceType',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '受理员',
                prop: 'acceptor',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '受理工号',
                prop: 'acceptorNumber',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '信息来源',
                prop: 'informationSources',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '来电类别',
                prop: 'callCategory',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'date',
                label: '录入时间',
                prop: 'inputTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 11,
              },
              {
                type: 'slot',
                label: '一级分类',
                prop: 'level1',
                value: '',
                isClearable: true,
                slotName: 'level1',
                span: 11,
              },
              {
                type: 'slot',
                label: '二级分类',
                prop: 'level2',
                slotName: 'level2',
                isClearable: true,
                span: 11,
              },
              {
                type: 'slot',
                label: '三级分类',
                prop: 'level3',
                slotName: 'level3',
                isClearable: true,
                span: 11,
              },
              {
                type: 'slot',
                label: '四级分类',
                prop: 'level4',
                slotName: 'level4',
                isClearable: true,
                span: 11,
              },
              {
                type: 'slot',
                label: '五级分类',
                prop: 'level5',
                slotName: 'level5',
                isClearable: true,
                span: 11,
              },
              {
                type: 'selectSearch',
                label: '工单类型',
                prop: 'orderType',
                code:'1004',
                isClearable: true,
                span: 11,
              },
              {
                type: 'selectSearch',
                label: '回复类型',
                prop: 'replyType',
                code:'1079',
                isClearable: true,
                span: 11,
              },
              {
                type: 'date',
                label: '回复（回退或申请）时间',
                prop: 'fallbackTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '回复（回退或申请）部门',
                prop: 'replyDepartment',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'textarea',
                label: '办理情况或回退（延期）理由：',
                prop: 'handleBackoff',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '回退意见：',
                prop: 'backOffOpinion',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '领导意见：',
                prop: 'leaderOpinion',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '签发人',
                prop: 'isSuer',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '联系人1：',
                prop: 'contact_1',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '联系电话1：',
                prop: 'contactPhone_1',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'date',
                label: '申请延期至：',
                prop: 'applyDelayTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '申请延期天数：',
                prop: 'applyDelayDay',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '答复来电人情况：',
                prop: 'replyCaller',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '答复人：',
                prop: 'replyPer',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'date',
                label: '答复时间：',
                prop: 'replyTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '答复电话：',
                prop: 'replyPhone',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '下级单位：',
                prop: 'subordinateUnit',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'date',
                label: '下级回复时间：',
                prop: 'subordinateReplyTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 11,
              },
              {
                type: 'textarea',
                label: '备注',
                prop: 'remarks',
                value: '',
                isClearable: true,
                span: 22,
              },
        ],
        rules:{
          officeName: [{ required: true, message: '请选择组织机构', trigger: 'blur' }],
          concludeTime: [{ required: true, message: '请输入办结时限', trigger: 'blur' }],
          contactNumber: [{ validator:validator.phoneNumber, trigger: ['blur']  }],
          problemDescription: [{ required: true, message: '请输入问题描述', trigger: ['change','blur'] }],
          transferOpinions: [{ required: true, message: '请输入转办意见', trigger: ['change','blur'] }],
          orderNo: [{ required: true, message: '请输入工单编号', trigger: 'blur' }],
          receivingTime: [{ required: true, message: '请输入接收时间', trigger: 'blur' }],
          urgency:[{ required: true, message: '请选择紧急程度', trigger: ['change','blur' ]}],
          isSecrecy:[{ required: true, message: '请选择是否需要保密', trigger: ['change','blur' ]}],
          isReply:[{ required: true, message: '请选择是否需要回复', trigger: ['change','blur' ]}],
          transferor:[{ required: true, message: '请输入转办人', trigger: ['blur' ]}],
          acceptanceType:[{ required: true, message: '请输入受理类型', trigger: ['blur' ]}],
          acceptor:[{ required: true, message: '请输入受理员', trigger: ['blur' ]}],
          acceptorNumber:[{ required: true, message: '请输入受理员工号', trigger: ['blur' ]}],
          informationSources:[{ required: true, message: '请输入信息来源', trigger: ['blur' ]}],
          callCategory:[{ required: true, message: '请输入来电类型', trigger: ['blur' ]}],
          inputTime:[{ required: true, message: '请输入录入时间', trigger: ['blur' ]}],
          orderType:[{ required: true, message: '请输入工单类型', trigger: ['blur' ]}],
          subordinateUnit:[{ required: true, message: '请输入下级单位', trigger: ['blur' ]}],
          level1:[{ required: true, message: '请选择一级分类', trigger: ['change','blur' ]}],
          level2:[{ required: true, message: '请选择二级分类', trigger: ['change','blur' ]}],
        }
    }

    return {
      InfoFormConfig
    }
}