// import {  } from '@/api/SocialGovernance/build'

export function renderTable() {
    const InfoFormConfig = {
        gutter:10,
        formItems: [
            {
                type: 'slot',
              label: '组织机构',
               prop: 'officeName',
                slotName:'status',
                span: 11,
              },
              {
                type: 'date',
                label: '办结时限',
                prop: 'concludeTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 8,
              },
              {
                type: 'Input',
                label: '联系人',
                prop: 'contacts',
                value: '',
                placeholder: '请输入楼号',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '联系电话',
                prop: 'contactNumber',
                value: '',
                placeholder: '请输入联系电话',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '问题描述',
                prop: 'problemDescription',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '转办意见',
                prop: 'transferOpinions',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '工单编号',
                prop: 'orderNO',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'date',
                label: '接收时间',
                prop: 'receivingTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 8,
              },
              {
                type: 'Input',
                label: '地址',
                prop: 'address',
                value: '',
                placeholder: '请输入地址',
                isClearable: true,
                span: 11,
              },
              {
                type: 'selectSearch',
                label: '紧急程度',
                prop: 'urgency',
                placeholder: '请选择紧急程度',
                code:'1004',
                isClearable: true,
                span: 11,
              },
              {
                type: 'selectSearch',
                label: '是否保密',
                prop: 'isSecrecy',
                code:'1004',
                isClearable: true,
                span: 11,
              },
              {
                type: 'selectSearch',
                label: '是否回复',
                prop: 'isReply',
                code:'1004',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '回复备注',
                prop: 'replyRemarks',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '办理轨迹',
                prop: 'handlingTrack',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '转办人',
                prop: 'transferor',
                value: '',
                placeholder: '请输入转办人',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '备注',
                prop: 'remarks',
                value: '',
                placeholder: '请输入备注',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '受理类型',
                prop: 'acceptanceType',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '受理员',
                prop: 'acceptor',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '受理工号',
                prop: 'acceptorNumber',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '信息来源',
                prop: 'informationSources',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '来电类别',
                prop: 'callCategory',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'date',
                label: '录入时间',
                prop: 'inputTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 8,
              },
              {
                type: 'Input',
                label: '一级分类',
                prop: 'level_1',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '二级分类',
                prop: 'level_2',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '三级分类',
                prop: 'level_3',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '四级分类',
                prop: 'level_4',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '五级分类',
                prop: 'level_5',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'selectSearch',
                label: '工单类型',
                prop: 'orderType',
                code:'1004',
                isClearable: true,
                span: 11,
              },
              {
                type: 'selectSearch',
                label: '回复类型',
                prop: 'replyType',
                code:'1004',
                isClearable: true,
                span: 11,
              },
              {
                type: 'date',
                label: '回复（回退或申请）时间',
                prop: 'fallbackTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 8,
              },
              {
                type: 'Input',
                label: '回复（回退或申请）部门',
                prop: 'replyDepartment',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '办理情况或回退（延期）理由：',
                prop: 'handleBackoff',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '回退意见：',
                prop: 'backOffOpinion',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '领导意见：',
                prop: 'leaderOpinion',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '签发人',
                prop: 'isSuer',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '联系人1：',
                prop: 'contact_1',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '联系电话1：',
                prop: 'contactPhone_1',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'date',
                label: '申请延期至：',
                prop: 'applyDelayTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 8,
              },
              {
                type: 'Input',
                label: '申请延期天数：',
                prop: 'applyDelayDay',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '答复来电人情况：',
                prop: 'replyCaller',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '答复人：',
                prop: 'replyPer',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'date',
                label: '答复时间：',
                prop: 'replyTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 8,
              },
              {
                type: 'Input',
                label: '答复电话：',
                prop: 'replyPhone',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'Input',
                label: '下级单位：',
                prop: 'subordinateUnit',
                value: '',
                isClearable: true,
                span: 11,
              },
              {
                type: 'date',
                label: '下级回复时间：',
                prop: 'subordinateReplyTime',
                value: '',
                format: 'YYYY-MM-DD HH:mm:ss',
                isClearable: true,
                span: 8,
              },
        ]
    }

    return {
      InfoFormConfig
    }
}