// import {  } from '@/api/SocialGovernance/build'

export function renderTable() {
  const ListFormConfig = {
    gutter: 10,
    formItems: [
      {
        type: 'Input',
        label: '手机号',
        prop: 'mobile',
        placeholder:'请输入手机号',
        span: 11,
      },
      // {
      //   type: 'date',
      //   label: '办结时限',
      //   prop: 'concludeTime',
      //   value: '',
      //   format: 'YYYY-MM-DD HH:mm:ss',
      //   isClearable: true,
      //   span: 11,
      // },
      {
        type: 'Input',
        label: '企业ID',
        prop: 'userid',
        value: '',
        placeholder: '请输入企业ID',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '账号',
        prop: 'account',
        value: '',
        placeholder: '请输入账号',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '请求地址',
        prop: 'https',
        value: '',
        placeholder: '请输入请求地址',
        isClearable: true,
        span: 11,
      },
      {
        type: 'textarea',
        label: '短信内容',
        prop: 'content',
        placeholder: '请输入短信内容',
        value: '',
        isClearable: true,
        span: 22,
      },
      {
        type: 'Input',
        label: '本次任务序列ID',
        prop: 'taskid',
        value: '',
        isClearable: true,
        span: 11,
      },
      {
        type: 'date',
        label: '接收时间',
        prop: 'receivingTime',
        value: '',
        format: 'YYYY-MM-DD HH:mm:ss',
        isClearable: true,
        span: 11,
      },
      {
        type: 'textarea',
        label: '备注',
        prop: 'remarks',
        value: '',
        placeholder: '请输入备注',
        isClearable: true,
        span: 22,
      },
      {
        type: 'Input',
        label: '时间戳',
        prop: 'timeStamp',
        value: '',
        placeholder: '请输入时间戳',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '关联ID',
        prop: 'smokeAlarmId',
        value: '',
        placeholder: '请输入关联ID',
        isClearable: true,
        span: 11,
      },
      // {
      //   type: 'selectSearch',
      //   label: '紧急程度',
      //   prop: 'urgency',
      //   placeholder: '请选择紧急程度',
      //   code: '1004',
      //   isClearable: true,
      //   span: 11,
      // },
    ],
  }
  const TempFormConfig = {
    gutter: 10,
    formItems: [
      {
        type: 'selectSearch',
        label: '模板类型',
        prop: 'urgency',
        placeholder: '请选择模板类型',
        code: '1004',
        isClearable: true,
        span: 11,
      },
      {
        type: 'Input',
        label: '模板名称',
        prop: 'mobile',
        placeholder:'请输入模板名称',
        span: 11,
      },
      {
        type: 'textarea',
        label: '短信内容',
        prop: 'content',
        placeholder: '请输入短信内容',
        value: '',
        isClearable: true,
        span: 22,
      },
      {
        type: 'slot',
        label: '填写规则',
        prop: '',
        slotName:'rule',
        span: 22,
      },
    ],
  }

  return {
    ListFormConfig,
    TempFormConfig,
  }
}
